### ISSUE TITLE
Class 'LynX39\LaraPdfMerger\PDFManage' not found

### ISSUE THREAD

**Issue by carlituxman** [LynX39/lara-pdf-merger#1]
I have this error:

Class 'LynX39\LaraPdfMerger\PDFManage' not found

what can be the problem, I do it all the instructions to install

**Comment by carlituxman** [comment]
The pacakage have a little bug, in local it works but in webfaction server fails, the problem is with the name of class is: class PDFManage and should be class PdfManage

**Comment by LynX39** [comment]
Hi @carlituxman, thanks for issue.
Resolved!

**Comment by carlituxman** [comment]
Why the composer update don't update this??
